# Generated by Django 4.2.1 on 2023-05-18 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(max_length=500, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Images_pr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('image_pr', models.ImageField(max_length=500, upload_to='')),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('step_id', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('time_error', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=10)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True)),
                ('imagen_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.images')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.job')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.job'),
        ),
    ]
