# Generated by Django 4.2.1 on 2023-05-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('process', 'PROCESS'), ('success', 'SUCCESS'), ('failure', 'FAILURE')], default='process', max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.images')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='api.job')),
            ],
        ),
    ]
