# Generated by Django 4.2.1 on 2023-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='end_time',
            field=models.DateTimeField(blank=True, default=' ', null=True),
        ),
    ]
