# Generated by Django 4.2.1 on 2023-05-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imagen',
            field=models.ImageField(blank='', default='', max_length=50, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images_pr',
            name='image_pr',
            field=models.ImageField(blank='', default='', max_length=50, upload_to='imagespr/'),
        ),
    ]
